### ISSUE TITLE
not found folder.png 

### ISSUE THREAD

**Issue by Rahul-Yadav-1996** [adarshsingh26/RemoteBox#2]
when I run client.py it raised an error is folder.png not found or its not a directory ..
how to resolve this error .
can you provide  your Gmail id . 
thnx

**Comment by adarshsingh26** [comment]
Yes ,thanks for pointing it out .It was because of the `file icons folder` was  missing  which contains icons for the file manager(this feature is still in progress ) . I  have updated the repo you can check it now.
